version: "3.9"  # optional since v1.27.0


networks:
  laravel:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: webserver
    ports:
      - "8088:80"
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/ect/nginx/conf.d/default.conf
    depends_on:
      - php
      - mysql

    networks:
      - laravel 
  mysql:
    image: mysql:5.7.22
    container_name: mysql
    restart: unless-stopped
    tty: true
    ports: 
      - "4306:3606"
    volumes:
      - ./mysql:/var/lib/mysql

    environment:
      MYSQL_DATABASE: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: server
      MYSQL_ROOT_PASSWORD:  server
      SERVICE_TAG: dev
      SERVICE_NAME: mysql
    networks:
      - laravel
  php:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php
    volumes:
      - ./src:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - laravel

